# Before 'make install' is performed this script should be runnable with
# 'make test'. After 'make install' it should work as 'perl OpenVR.t'

#########################

# change 'tests => 2' to 'tests => last_test_to_print';

use strict;
use warnings;

use Test::More tests => 1;
use OpenVR;

my $fail = 0;
foreach my $constname (qw(
	ChaperoneCalibrationState_Error
	ChaperoneCalibrationState_Error_BaseStationConflict
	ChaperoneCalibrationState_Error_BaseStationUninitalized
	ChaperoneCalibrationState_Error_CollisionBoundsInvalid
	ChaperoneCalibrationState_Error_PlayAreaInvalid
	ChaperoneCalibrationState_OK ChaperoneCalibrationState_Warning
	ChaperoneCalibrationState_Warning_BaseStationMayHaveMoved
	ChaperoneCalibrationState_Warning_BaseStationRemoved
	ChaperoneCalibrationState_Warning_SeatedBoundsInvalid
	EChaperoneConfigFile_Live EChaperoneConfigFile_Temp
	EChaperoneImportFlags_EChaperoneImport_BoundsOnly
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_ADVANCED
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_BEGINNER
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_COUNT
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_INTERMEDIATE
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_NONE
	ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_SQUARES
	EColorSpace_ColorSpace_Auto EColorSpace_ColorSpace_Gamma
	EColorSpace_ColorSpace_Linear
	EDeviceActivityLevel_k_EDeviceActivityLevel_Idle
	EDeviceActivityLevel_k_EDeviceActivityLevel_Standby
	EDeviceActivityLevel_k_EDeviceActivityLevel_Unknown
	EDeviceActivityLevel_k_EDeviceActivityLevel_UserInteraction
	EDeviceActivityLevel_k_EDeviceActivityLevel_UserInteraction_Timeout
	EGamepadTextInputLineMode_k_EGamepadTextInputLineModeMultipleLines
	EGamepadTextInputLineMode_k_EGamepadTextInputLineModeSingleLine
	EGamepadTextInputMode_k_EGamepadTextInputModeNormal
	EGamepadTextInputMode_k_EGamepadTextInputModePassword
	EGamepadTextInputMode_k_EGamepadTextInputModeSubmit
	EGraphicsAPIConvention_API_DirectX EGraphicsAPIConvention_API_OpenGL
	EOverlayDirection_OverlayDirection_Count
	EOverlayDirection_OverlayDirection_Down
	EOverlayDirection_OverlayDirection_Left
	EOverlayDirection_OverlayDirection_Right
	EOverlayDirection_OverlayDirection_Up
	ETrackedControllerRole_TrackedControllerRole_Invalid
	ETrackedControllerRole_TrackedControllerRole_LeftHand
	ETrackedControllerRole_TrackedControllerRole_RightHand
	ETrackedDeviceClass_TrackedDeviceClass_Controller
	ETrackedDeviceClass_TrackedDeviceClass_HMD
	ETrackedDeviceClass_TrackedDeviceClass_Invalid
	ETrackedDeviceClass_TrackedDeviceClass_Other
	ETrackedDeviceClass_TrackedDeviceClass_TrackingReference
	ETrackedDeviceProperty_Prop_AllWirelessDongleDescriptions_String
	ETrackedDeviceProperty_Prop_AttachedDeviceId_String
	ETrackedDeviceProperty_Prop_AudioFirmwareVersion_Uint64
	ETrackedDeviceProperty_Prop_Axis0Type_Int32
	ETrackedDeviceProperty_Prop_Axis1Type_Int32
	ETrackedDeviceProperty_Prop_Axis2Type_Int32
	ETrackedDeviceProperty_Prop_Axis3Type_Int32
	ETrackedDeviceProperty_Prop_Axis4Type_Int32
	ETrackedDeviceProperty_Prop_BlockServerShutdown_Bool
	ETrackedDeviceProperty_Prop_CameraCompatibilityMode_Int32
	ETrackedDeviceProperty_Prop_CameraFirmwareDescription_String
	ETrackedDeviceProperty_Prop_CameraFirmwareVersion_Uint64
	ETrackedDeviceProperty_Prop_CameraToHeadTransform_Matrix34
	ETrackedDeviceProperty_Prop_CanUnifyCoordinateSystemWithHmd_Bool
	ETrackedDeviceProperty_Prop_ConnectedWirelessDongle_String
	ETrackedDeviceProperty_Prop_ContainsProximitySensor_Bool
	ETrackedDeviceProperty_Prop_ControllerRoleHint_Int32
	ETrackedDeviceProperty_Prop_CurrentUniverseId_Uint64
	ETrackedDeviceProperty_Prop_DeviceBatteryPercentage_Float
	ETrackedDeviceProperty_Prop_DeviceCanPowerOff_Bool
	ETrackedDeviceProperty_Prop_DeviceClass_Int32
	ETrackedDeviceProperty_Prop_DeviceIsCharging_Bool
	ETrackedDeviceProperty_Prop_DeviceIsWireless_Bool
	ETrackedDeviceProperty_Prop_DeviceProvidesBatteryStatus_Bool
	ETrackedDeviceProperty_Prop_DisplayBootloaderVersion_Uint64
	ETrackedDeviceProperty_Prop_DisplayFPGAVersion_Uint64
	ETrackedDeviceProperty_Prop_DisplayFirmwareVersion_Uint64
	ETrackedDeviceProperty_Prop_DisplayFrequency_Float
	ETrackedDeviceProperty_Prop_DisplayGCBlackClamp_Float
	ETrackedDeviceProperty_Prop_DisplayGCImage_String
	ETrackedDeviceProperty_Prop_DisplayGCOffset_Float
	ETrackedDeviceProperty_Prop_DisplayGCPrescale_Float
	ETrackedDeviceProperty_Prop_DisplayGCScale_Float
	ETrackedDeviceProperty_Prop_DisplayGCType_Int32
	ETrackedDeviceProperty_Prop_DisplayHardwareVersion_Uint64
	ETrackedDeviceProperty_Prop_DisplayMCImageLeft_String
	ETrackedDeviceProperty_Prop_DisplayMCImageRight_String
	ETrackedDeviceProperty_Prop_DisplayMCOffset_Float
	ETrackedDeviceProperty_Prop_DisplayMCScale_Float
	ETrackedDeviceProperty_Prop_DisplayMCType_Int32
	ETrackedDeviceProperty_Prop_DisplaySuppressed_Bool
	ETrackedDeviceProperty_Prop_DongleVersion_Uint64
	ETrackedDeviceProperty_Prop_DriverVersion_String
	ETrackedDeviceProperty_Prop_EdidProductID_Int32
	ETrackedDeviceProperty_Prop_EdidVendorID_Int32
	ETrackedDeviceProperty_Prop_FPGAVersion_Uint64
	ETrackedDeviceProperty_Prop_FieldOfViewBottomDegrees_Float
	ETrackedDeviceProperty_Prop_FieldOfViewLeftDegrees_Float
	ETrackedDeviceProperty_Prop_FieldOfViewRightDegrees_Float
	ETrackedDeviceProperty_Prop_FieldOfViewTopDegrees_Float
	ETrackedDeviceProperty_Prop_FirmwareVersion_Uint64
	ETrackedDeviceProperty_Prop_Firmware_ForceUpdateRequired_Bool
	ETrackedDeviceProperty_Prop_Firmware_ManualUpdateURL_String
	ETrackedDeviceProperty_Prop_Firmware_ManualUpdate_Bool
	ETrackedDeviceProperty_Prop_Firmware_ProgrammingTarget_String
	ETrackedDeviceProperty_Prop_Firmware_UpdateAvailable_Bool
	ETrackedDeviceProperty_Prop_HardwareRevision_String
	ETrackedDeviceProperty_Prop_HardwareRevision_Uint64
	ETrackedDeviceProperty_Prop_HasCamera_Bool
	ETrackedDeviceProperty_Prop_IsOnDesktop_Bool
	ETrackedDeviceProperty_Prop_LensCenterLeftU_Float
	ETrackedDeviceProperty_Prop_LensCenterLeftV_Float
	ETrackedDeviceProperty_Prop_LensCenterRightU_Float
	ETrackedDeviceProperty_Prop_LensCenterRightV_Float
	ETrackedDeviceProperty_Prop_ManufacturerName_String
	ETrackedDeviceProperty_Prop_ModeLabel_String
	ETrackedDeviceProperty_Prop_ModelNumber_String
	ETrackedDeviceProperty_Prop_PreviousUniverseId_Uint64
	ETrackedDeviceProperty_Prop_RadioVersion_Uint64
	ETrackedDeviceProperty_Prop_RenderModelName_String
	ETrackedDeviceProperty_Prop_ReportsTimeSinceVSync_Bool
	ETrackedDeviceProperty_Prop_ScreenshotHorizontalFieldOfViewDegrees_Float
	ETrackedDeviceProperty_Prop_ScreenshotVerticalFieldOfViewDegrees_Float
	ETrackedDeviceProperty_Prop_SecondsFromVsyncToPhotons_Float
	ETrackedDeviceProperty_Prop_SerialNumber_String
	ETrackedDeviceProperty_Prop_StatusDisplayTransform_Matrix34
	ETrackedDeviceProperty_Prop_SupportedButtons_Uint64
	ETrackedDeviceProperty_Prop_TrackingFirmwareVersion_String
	ETrackedDeviceProperty_Prop_TrackingRangeMaximumMeters_Float
	ETrackedDeviceProperty_Prop_TrackingRangeMinimumMeters_Float
	ETrackedDeviceProperty_Prop_TrackingSystemName_String
	ETrackedDeviceProperty_Prop_UserHeadToEyeDepthMeters_Float
	ETrackedDeviceProperty_Prop_UserIpdMeters_Float
	ETrackedDeviceProperty_Prop_VRCVersion_Uint64
	ETrackedDeviceProperty_Prop_VendorSpecific_Reserved_End
	ETrackedDeviceProperty_Prop_VendorSpecific_Reserved_Start
	ETrackedDeviceProperty_Prop_WillDriftInYaw_Bool
	ETrackedPropertyError_TrackedProp_BufferTooSmall
	ETrackedPropertyError_TrackedProp_CouldNotContactServer
	ETrackedPropertyError_TrackedProp_InvalidDevice
	ETrackedPropertyError_TrackedProp_NotYetAvailable
	ETrackedPropertyError_TrackedProp_StringExceedsMaximumLength
	ETrackedPropertyError_TrackedProp_Success
	ETrackedPropertyError_TrackedProp_UnknownProperty
	ETrackedPropertyError_TrackedProp_ValueNotProvidedByDevice
	ETrackedPropertyError_TrackedProp_WrongDataType
	ETrackedPropertyError_TrackedProp_WrongDeviceClass
	ETrackingResult_TrackingResult_Calibrating_InProgress
	ETrackingResult_TrackingResult_Calibrating_OutOfRange
	ETrackingResult_TrackingResult_Running_OK
	ETrackingResult_TrackingResult_Running_OutOfRange
	ETrackingResult_TrackingResult_Uninitialized
	ETrackingUniverseOrigin_TrackingUniverseRawAndUncalibrated
	ETrackingUniverseOrigin_TrackingUniverseSeated
	ETrackingUniverseOrigin_TrackingUniverseStanding
	EVRApplicationError_VRApplicationError_AppKeyAlreadyExists
	EVRApplicationError_VRApplicationError_ApplicationAlreadyRunning
	EVRApplicationError_VRApplicationError_ApplicationAlreadyStarting
	EVRApplicationError_VRApplicationError_BufferTooSmall
	EVRApplicationError_VRApplicationError_IPCFailed
	EVRApplicationError_VRApplicationError_InvalidApplication
	EVRApplicationError_VRApplicationError_InvalidIndex
	EVRApplicationError_VRApplicationError_InvalidManifest
	EVRApplicationError_VRApplicationError_InvalidParameter
	EVRApplicationError_VRApplicationError_IsTemplate
	EVRApplicationError_VRApplicationError_LaunchFailed
	EVRApplicationError_VRApplicationError_LaunchInProgress
	EVRApplicationError_VRApplicationError_NoApplication
	EVRApplicationError_VRApplicationError_NoManifest
	EVRApplicationError_VRApplicationError_None
	EVRApplicationError_VRApplicationError_OldApplicationQuitting
	EVRApplicationError_VRApplicationError_PropertyNotSet
	EVRApplicationError_VRApplicationError_TransitionAborted
	EVRApplicationError_VRApplicationError_UnknownApplication
	EVRApplicationError_VRApplicationError_UnknownProperty
	EVRApplicationProperty_VRApplicationProperty_Arguments_String
	EVRApplicationProperty_VRApplicationProperty_BinaryPath_String
	EVRApplicationProperty_VRApplicationProperty_Description_String
	EVRApplicationProperty_VRApplicationProperty_ImagePath_String
	EVRApplicationProperty_VRApplicationProperty_IsDashboardOverlay_Bool
	EVRApplicationProperty_VRApplicationProperty_IsInstanced_Bool
	EVRApplicationProperty_VRApplicationProperty_IsTemplate_Bool
	EVRApplicationProperty_VRApplicationProperty_LastLaunchTime_Uint64
	EVRApplicationProperty_VRApplicationProperty_LaunchType_String
	EVRApplicationProperty_VRApplicationProperty_Name_String
	EVRApplicationProperty_VRApplicationProperty_NewsURL_String
	EVRApplicationProperty_VRApplicationProperty_Source_String
	EVRApplicationProperty_VRApplicationProperty_URL_String
	EVRApplicationProperty_VRApplicationProperty_WorkingDirectory_String
	EVRApplicationTransitionState_VRApplicationTransition_NewAppLaunched
	EVRApplicationTransitionState_VRApplicationTransition_None
	EVRApplicationTransitionState_VRApplicationTransition_OldAppQuitSent
	EVRApplicationTransitionState_VRApplicationTransition_WaitingForExternalLaunch
	EVRApplicationType_VRApplication_Background
	EVRApplicationType_VRApplication_Max
	EVRApplicationType_VRApplication_Other
	EVRApplicationType_VRApplication_Overlay
	EVRApplicationType_VRApplication_Scene
	EVRApplicationType_VRApplication_SteamWatchdog
	EVRApplicationType_VRApplication_Utility
	EVRApplicationType_VRApplication_VRMonitor EVRButtonId_k_EButton_A
	EVRButtonId_k_EButton_ApplicationMenu EVRButtonId_k_EButton_Axis0
	EVRButtonId_k_EButton_Axis1 EVRButtonId_k_EButton_Axis2
	EVRButtonId_k_EButton_Axis3 EVRButtonId_k_EButton_Axis4
	EVRButtonId_k_EButton_DPad_Down EVRButtonId_k_EButton_DPad_Left
	EVRButtonId_k_EButton_DPad_Right EVRButtonId_k_EButton_DPad_Up
	EVRButtonId_k_EButton_Dashboard_Back EVRButtonId_k_EButton_Grip
	EVRButtonId_k_EButton_Max EVRButtonId_k_EButton_SteamVR_Touchpad
	EVRButtonId_k_EButton_SteamVR_Trigger EVRButtonId_k_EButton_System
	EVRComponentProperty_VRComponentProperty_IsPressed
	EVRComponentProperty_VRComponentProperty_IsScrolled
	EVRComponentProperty_VRComponentProperty_IsStatic
	EVRComponentProperty_VRComponentProperty_IsTouched
	EVRComponentProperty_VRComponentProperty_IsVisible
	EVRCompositorError_VRCompositorError_DoNotHaveFocus
	EVRCompositorError_VRCompositorError_IncompatibleVersion
	EVRCompositorError_VRCompositorError_IndexOutOfRange
	EVRCompositorError_VRCompositorError_InvalidTexture
	EVRCompositorError_VRCompositorError_IsNotSceneApplication
	EVRCompositorError_VRCompositorError_None
	EVRCompositorError_VRCompositorError_RequestFailed
	EVRCompositorError_VRCompositorError_SharedTexturesNotSupported
	EVRCompositorError_VRCompositorError_TextureIsOnWrongDevice
	EVRCompositorError_VRCompositorError_TextureUsesUnsupportedFormat
	EVRControllerAxisType_k_eControllerAxis_Joystick
	EVRControllerAxisType_k_eControllerAxis_None
	EVRControllerAxisType_k_eControllerAxis_TrackPad
	EVRControllerAxisType_k_eControllerAxis_Trigger
	EVRControllerEventOutputType_ControllerEventOutput_OSEvents
	EVRControllerEventOutputType_ControllerEventOutput_VREvents
	EVREventType_VREvent_ApplicationListUpdated
	EVREventType_VREvent_ApplicationMimeTypeLoad
	EVREventType_VREvent_ApplicationTransitionAborted
	EVREventType_VREvent_ApplicationTransitionNewAppStarted
	EVREventType_VREvent_ApplicationTransitionStarted
	EVREventType_VREvent_AudioSettingsHaveChanged
	EVREventType_VREvent_BackgroundSettingHasChanged
	EVREventType_VREvent_ButtonPress EVREventType_VREvent_ButtonTouch
	EVREventType_VREvent_ButtonUnpress EVREventType_VREvent_ButtonUntouch
	EVREventType_VREvent_CameraSettingsHaveChanged
	EVREventType_VREvent_ChaperoneDataHasChanged
	EVREventType_VREvent_ChaperoneSettingsHaveChanged
	EVREventType_VREvent_ChaperoneTempDataHasChanged
	EVREventType_VREvent_ChaperoneUniverseHasChanged
	EVREventType_VREvent_Compositor_ChaperoneBoundsHidden
	EVREventType_VREvent_Compositor_ChaperoneBoundsShown
	EVREventType_VREvent_Compositor_MirrorWindowHidden
	EVREventType_VREvent_Compositor_MirrorWindowShown
	EVREventType_VREvent_DashboardActivated
	EVREventType_VREvent_DashboardDeactivated
	EVREventType_VREvent_DashboardGuideButtonDown
	EVREventType_VREvent_DashboardGuideButtonUp
	EVREventType_VREvent_DashboardRequested
	EVREventType_VREvent_DashboardThumbSelected
	EVREventType_VREvent_DriverRequestedQuit
	EVREventType_VREvent_EnterStandbyMode
	EVREventType_VREvent_EnvironmentSettingsHaveChanged
	EVREventType_VREvent_FirmwareUpdateFinished
	EVREventType_VREvent_FirmwareUpdateStarted
	EVREventType_VREvent_FocusEnter EVREventType_VREvent_FocusLeave
	EVREventType_VREvent_HideKeyboard EVREventType_VREvent_HideRenderModels
	EVREventType_VREvent_ImageFailed EVREventType_VREvent_ImageLoaded
	EVREventType_VREvent_InputFocusCaptured
	EVREventType_VREvent_InputFocusChanged
	EVREventType_VREvent_InputFocusReleased EVREventType_VREvent_IpdChanged
	EVREventType_VREvent_KeyboardCharInput
	EVREventType_VREvent_KeyboardClosed EVREventType_VREvent_KeyboardDone
	EVREventType_VREvent_LeaveStandbyMode
	EVREventType_VREvent_MCImageUpdated
	EVREventType_VREvent_ModelSkinSettingsHaveChanged
	EVREventType_VREvent_MouseButtonDown EVREventType_VREvent_MouseButtonUp
	EVREventType_VREvent_MouseMove EVREventType_VREvent_None
	EVREventType_VREvent_Notification_BeginInteraction
	EVREventType_VREvent_Notification_Destroyed
	EVREventType_VREvent_Notification_Hidden
	EVREventType_VREvent_Notification_Shown
	EVREventType_VREvent_OverlayFocusChanged
	EVREventType_VREvent_OverlayGamepadFocusGained
	EVREventType_VREvent_OverlayGamepadFocusLost
	EVREventType_VREvent_OverlayHidden
	EVREventType_VREvent_OverlaySharedTextureChanged
	EVREventType_VREvent_OverlayShown
	EVREventType_VREvent_PerformanceTest_DisableCapture
	EVREventType_VREvent_PerformanceTest_EnableCapture
	EVREventType_VREvent_PerformanceTest_FidelityLevel
	EVREventType_VREvent_ProcessQuit EVREventType_VREvent_Quit
	EVREventType_VREvent_QuitAborted_UserPrompt
	EVREventType_VREvent_QuitAcknowledged EVREventType_VREvent_RenderToast
	EVREventType_VREvent_ReprojectionSettingHasChanged
	EVREventType_VREvent_RequestScreenshot
	EVREventType_VREvent_ResetDashboard
	EVREventType_VREvent_SceneApplicationChanged
	EVREventType_VREvent_SceneApplicationSecondaryRenderingStarted
	EVREventType_VREvent_SceneFocusChanged
	EVREventType_VREvent_SceneFocusGained
	EVREventType_VREvent_SceneFocusLost
	EVREventType_VREvent_ScreenshotFailed
	EVREventType_VREvent_ScreenshotProgressToDashboard
	EVREventType_VREvent_ScreenshotTaken
	EVREventType_VREvent_ScreenshotTriggered EVREventType_VREvent_Scroll
	EVREventType_VREvent_SeatedZeroPoseReset
	EVREventType_VREvent_ShowKeyboard EVREventType_VREvent_ShowRenderModels
	EVREventType_VREvent_StatusUpdate
	EVREventType_VREvent_SubmitScreenshotToDashboard
	EVREventType_VREvent_TouchPadMove
	EVREventType_VREvent_TrackedCamera_PauseVideoStream
	EVREventType_VREvent_TrackedCamera_ResumeVideoStream
	EVREventType_VREvent_TrackedCamera_StartVideoStream
	EVREventType_VREvent_TrackedCamera_StopVideoStream
	EVREventType_VREvent_TrackedDeviceActivated
	EVREventType_VREvent_TrackedDeviceDeactivated
	EVREventType_VREvent_TrackedDeviceRoleChanged
	EVREventType_VREvent_TrackedDeviceUpdated
	EVREventType_VREvent_TrackedDeviceUserInteractionEnded
	EVREventType_VREvent_TrackedDeviceUserInteractionStarted
	EVREventType_VREvent_VendorSpecific_Reserved_End
	EVREventType_VREvent_VendorSpecific_Reserved_Start
	EVREventType_VREvent_WatchdogWakeUpRequested EVREye_Eye_Left
	EVREye_Eye_Right EVRFirmwareError_VRFirmwareError_Fail
	EVRFirmwareError_VRFirmwareError_None
	EVRFirmwareError_VRFirmwareError_Success
	EVRInitError_VRInitError_Compositor_D3D11HardwareRequired
	EVRInitError_VRInitError_Compositor_Failed
	EVRInitError_VRInitError_Compositor_FirmwareRequiresUpdate
	EVRInitError_VRInitError_Compositor_OverlayInitFailed
	EVRInitError_VRInitError_Compositor_ScreenshotsInitFailed
	EVRInitError_VRInitError_Driver_CalibrationInvalid
	EVRInitError_VRInitError_Driver_Failed
	EVRInitError_VRInitError_Driver_HmdDisplayMirrored
	EVRInitError_VRInitError_Driver_HmdDisplayNotFound
	EVRInitError_VRInitError_Driver_HmdDriverIdOutOfBounds
	EVRInitError_VRInitError_Driver_HmdInUse
	EVRInitError_VRInitError_Driver_HmdUnknown
	EVRInitError_VRInitError_Driver_NotCalibrated
	EVRInitError_VRInitError_Driver_NotLoaded
	EVRInitError_VRInitError_Driver_RuntimeOutOfDate
	EVRInitError_VRInitError_Driver_TrackedDeviceInterfaceUnknown
	EVRInitError_VRInitError_Driver_Unknown
	EVRInitError_VRInitError_IPC_CompositorConnectFailed
	EVRInitError_VRInitError_IPC_CompositorInitFailed
	EVRInitError_VRInitError_IPC_CompositorInvalidConnectResponse
	EVRInitError_VRInitError_IPC_ConnectFailed
	EVRInitError_VRInitError_IPC_ConnectFailedAfterMultipleAttempts
	EVRInitError_VRInitError_IPC_Failed
	EVRInitError_VRInitError_IPC_MutexInitFailed
	EVRInitError_VRInitError_IPC_ServerInitFailed
	EVRInitError_VRInitError_IPC_SharedStateInitFailed
	EVRInitError_VRInitError_Init_AnotherAppLaunching
	EVRInitError_VRInitError_Init_AppInfoInitFailed
	EVRInitError_VRInitError_Init_FactoryNotFound
	EVRInitError_VRInitError_Init_FileNotFound
	EVRInitError_VRInitError_Init_HmdDriverIdIsNone
	EVRInitError_VRInitError_Init_HmdNotFound
	EVRInitError_VRInitError_Init_HmdNotFoundPresenceFailed
	EVRInitError_VRInitError_Init_InitCanceledByUser
	EVRInitError_VRInitError_Init_InstallationCorrupt
	EVRInitError_VRInitError_Init_InstallationNotFound
	EVRInitError_VRInitError_Init_InterfaceNotFound
	EVRInitError_VRInitError_Init_Internal
	EVRInitError_VRInitError_Init_InvalidApplicationType
	EVRInitError_VRInitError_Init_InvalidInterface
	EVRInitError_VRInitError_Init_LowPowerWatchdogNotSupported
	EVRInitError_VRInitError_Init_NoConfigPath
	EVRInitError_VRInitError_Init_NoLogPath
	EVRInitError_VRInitError_Init_NoServerForBackgroundApp
	EVRInitError_VRInitError_Init_NotAvailableToUtilityApps
	EVRInitError_VRInitError_Init_NotAvailableToWatchdogApps
	EVRInitError_VRInitError_Init_NotInitialized
	EVRInitError_VRInitError_Init_NotSupportedWithCompositor
	EVRInitError_VRInitError_Init_PathRegistryNotFound
	EVRInitError_VRInitError_Init_PathRegistryNotWritable
	EVRInitError_VRInitError_Init_Retry
	EVRInitError_VRInitError_Init_SettingsInitFailed
	EVRInitError_VRInitError_Init_ShuttingDown
	EVRInitError_VRInitError_Init_TooManyObjects
	EVRInitError_VRInitError_Init_UserConfigDirectoryInvalid
	EVRInitError_VRInitError_Init_VRClientDLLNotFound
	EVRInitError_VRInitError_Init_VRMonitorNotFound
	EVRInitError_VRInitError_Init_VRMonitorStartupFailed
	EVRInitError_VRInitError_Init_WatchdogDisabledInSettings
	EVRInitError_VRInitError_None
	EVRInitError_VRInitError_Steam_SteamInstallationNotFound
	EVRInitError_VRInitError_Unknown
	EVRInitError_VRInitError_VendorSpecific_HmdFound_CantOpenDevice
	EVRInitError_VRInitError_VendorSpecific_HmdFound_CantReadFirmwareVersion
	EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigFailedSanityCheck
	EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigTooBig
	EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigTooSmall
	EVRInitError_VRInitError_VendorSpecific_HmdFound_NoStoredConfig
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataNext
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataStart
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToInitZLib
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToRequestConfigStart
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToSendUserDataStart
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UserDataAddressRange
	EVRInitError_VRInitError_VendorSpecific_HmdFound_UserDataError
	EVRInitError_VRInitError_VendorSpecific_UnableToConnectToOculusRuntime
	EVRMouseButton_VRMouseButton_Left EVRMouseButton_VRMouseButton_Middle
	EVRMouseButton_VRMouseButton_Right
	EVRNotificationError_VRNotificationError_InvalidNotificationId
	EVRNotificationError_VRNotificationError_InvalidOverlayHandle
	EVRNotificationError_VRNotificationError_NotificationQueueFull
	EVRNotificationError_VRNotificationError_OK
	EVRNotificationError_VRNotificationError_SystemWithUserValueAlreadyExists
	EVRNotificationStyle_Application EVRNotificationStyle_Contact_Active
	EVRNotificationStyle_Contact_Disabled
	EVRNotificationStyle_Contact_Enabled EVRNotificationStyle_None
	EVRNotificationType_Persistent EVRNotificationType_Transient
	EVRNotificationType_Transient_SystemWithUserValue
	EVROverlayError_VROVerlayError_KeyboardAlreadyInUse
	EVROverlayError_VROverlayError_ArrayTooSmall
	EVROverlayError_VROverlayError_InvalidHandle
	EVROverlayError_VROverlayError_InvalidParameter
	EVROverlayError_VROverlayError_InvalidTexture
	EVROverlayError_VROverlayError_InvalidTrackedDevice
	EVROverlayError_VROverlayError_KeyInUse
	EVROverlayError_VROverlayError_KeyTooLong
	EVROverlayError_VROverlayError_NameTooLong
	EVROverlayError_VROverlayError_NoNeighbor
	EVROverlayError_VROverlayError_None
	EVROverlayError_VROverlayError_OverlayLimitExceeded
	EVROverlayError_VROverlayError_PermissionDenied
	EVROverlayError_VROverlayError_RequestFailed
	EVROverlayError_VROverlayError_ThumbnailCantBeDestroyed
	EVROverlayError_VROverlayError_UnableToLoadFile
	EVROverlayError_VROverlayError_UnknownOverlay
	EVROverlayError_VROverlayError_WrongTransformType
	EVROverlayError_VROverlayError_WrongVisibilityType
	EVRRenderModelError_VRRenderModelError_BufferTooSmall
	EVRRenderModelError_VRRenderModelError_InvalidArg
	EVRRenderModelError_VRRenderModelError_InvalidModel
	EVRRenderModelError_VRRenderModelError_InvalidTexture
	EVRRenderModelError_VRRenderModelError_Loading
	EVRRenderModelError_VRRenderModelError_MultipleShapes
	EVRRenderModelError_VRRenderModelError_MultipleTextures
	EVRRenderModelError_VRRenderModelError_NoShapes
	EVRRenderModelError_VRRenderModelError_None
	EVRRenderModelError_VRRenderModelError_NotEnoughNormals
	EVRRenderModelError_VRRenderModelError_NotEnoughTexCoords
	EVRRenderModelError_VRRenderModelError_NotSupported
	EVRRenderModelError_VRRenderModelError_TooManyVertices
	EVRScreenshotError_VRScreenshotError_BufferTooSmall
	EVRScreenshotError_VRScreenshotError_IncompatibleVersion
	EVRScreenshotError_VRScreenshotError_None
	EVRScreenshotError_VRScreenshotError_NotFound
	EVRScreenshotError_VRScreenshotError_RequestFailed
	EVRScreenshotError_VRScreenshotError_ScreenshotAlreadyInProgress
	EVRScreenshotPropertyFilenames_VRScreenshotPropertyFilenames_Preview
	EVRScreenshotPropertyFilenames_VRScreenshotPropertyFilenames_VR
	EVRScreenshotType_VRScreenshotType_Cubemap
	EVRScreenshotType_VRScreenshotType_Mono
	EVRScreenshotType_VRScreenshotType_MonoPanorama
	EVRScreenshotType_VRScreenshotType_None
	EVRScreenshotType_VRScreenshotType_Stereo
	EVRScreenshotType_VRScreenshotType_StereoPanorama
	EVRSettingsError_VRSettingsError_IPCFailed
	EVRSettingsError_VRSettingsError_None
	EVRSettingsError_VRSettingsError_ReadFailed
	EVRSettingsError_VRSettingsError_WriteFailed EVRState_VRState_NotReady
	EVRState_VRState_Off EVRState_VRState_Ready
	EVRState_VRState_Ready_Alert EVRState_VRState_Ready_Alert_Low
	EVRState_VRState_Searching EVRState_VRState_Searching_Alert
	EVRState_VRState_Standby EVRState_VRState_Undefined
	EVRSubmitFlags_Submit_Default EVRSubmitFlags_Submit_GlRenderBuffer
	EVRSubmitFlags_Submit_LensDistortionAlreadyApplied
	EVRTrackedCameraError_VRTrackedCameraError_FailedToGetGLTextureId
	EVRTrackedCameraError_VRTrackedCameraError_FrameBufferingFailure
	EVRTrackedCameraError_VRTrackedCameraError_IPCFailure
	EVRTrackedCameraError_VRTrackedCameraError_InvalidArgument
	EVRTrackedCameraError_VRTrackedCameraError_InvalidFrameBufferSize
	EVRTrackedCameraError_VRTrackedCameraError_InvalidFrameHeaderVersion
	EVRTrackedCameraError_VRTrackedCameraError_InvalidGLTextureId
	EVRTrackedCameraError_VRTrackedCameraError_InvalidHandle
	EVRTrackedCameraError_VRTrackedCameraError_InvalidSharedTextureHandle
	EVRTrackedCameraError_VRTrackedCameraError_NoFrameAvailable
	EVRTrackedCameraError_VRTrackedCameraError_None
	EVRTrackedCameraError_VRTrackedCameraError_NotSupportedForThisDevice
	EVRTrackedCameraError_VRTrackedCameraError_OperationFailed
	EVRTrackedCameraError_VRTrackedCameraError_OutOfHandles
	EVRTrackedCameraError_VRTrackedCameraError_SharedMemoryFailure
	EVRTrackedCameraError_VRTrackedCameraError_SharedTextureFailure
	EVRTrackedCameraError_VRTrackedCameraError_StreamSetupFailure
	EVRTrackedCameraFrameType_MAX_CAMERA_FRAME_TYPES
	EVRTrackedCameraFrameType_VRTrackedCameraFrameType_Distorted
	EVRTrackedCameraFrameType_VRTrackedCameraFrameType_MaximumUndistorted
	EVRTrackedCameraFrameType_VRTrackedCameraFrameType_Undistorted
	VROverlayFlags_AcceptsGamepadEvents
	VROverlayFlags_Curved VROverlayFlags_NoDashboardTab VROverlayFlags_None
	VROverlayFlags_Panorama VROverlayFlags_RGSS4X
	VROverlayFlags_SendVRScrollEvents VROverlayFlags_SendVRTouchpadEvents
	VROverlayFlags_ShowGamepadFocus VROverlayFlags_ShowTouchPadScrollWheel
	VROverlayFlags_SideBySide_Crossed VROverlayFlags_SideBySide_Parallel
	VROverlayFlags_SortWithNonSceneOverlays VROverlayFlags_StereoPanorama
	VROverlayFlags_TransferOwnershipToInternalProcess
	VROverlayInputMethod_Mouse VROverlayInputMethod_None
	VROverlayTransformType_VROverlayTransform_Absolute
	VROverlayTransformType_VROverlayTransform_SystemOverlay
	VROverlayTransformType_VROverlayTransform_TrackedComponent
	VROverlayTransformType_VROverlayTransform_TrackedDeviceRelative)) {
  next if (eval "my \$a = $constname; 1");
  if ($@ =~ /^Your vendor has not defined OpenVR macro $constname/) {
    print "# pass: $@";
  } else {
    print "# fail: $@";
    $fail = 1;
  }

}

ok( $fail == 0 , 'Constants' );
#########################

# Insert your test code below, the Test::More module is use()ed here so read
# its man page ( perldoc Test::More ) for help writing this test script.

